# Generated by Django 5.0.2 on 2024-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
