# Generated by Django 5.0.2 on 2024-03-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_field_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=100, null=True, verbose_name='درس مورد نظر'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.FloatField(verbose_name='نمره'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='فامیلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(verbose_name='شماره دانش آموزی'),
        ),
    ]
